version: "0.0.3"

services:

  peer1:
    image: discovery
    ports:
      - "8071:8071"
    hostname: peer1
    environment:
      - spring.profiles.active=peer1
      - PORT=8071
      - HOST=192.168.0.104

  peer2:
    image: discovery
    ports:
      - "8072:8072"
    hostname: peer2
    environment:
      - spring.profiles.active=peer2
      - PORT=8072
      - HOST=192.168.0.104

  microservice-provider-user:
    image: frodewy/microservice-provider-user:0.0.3

    environment:
      - HOST1=192.168.0.104
      - HOST2=192.168.0.104

  microservice-consumer-movie:
    image: frodewy/microservice-consumer-movie:0.0.3

    environment:
      - HOST1=192.168.0.104
      - HOST2=192.168.0.104

  microservice-gataway-zuul:
    image: frodewy/microservice-gataway-zuul:0.0.3

    environment:
      - HOST1=192.168.0.104
      - HOST2=192.168.0.104