parameters:
  upload-path: C:/Users/wangyang/Desktop/
server:
  port: 8060
spring:
  application:
    name: microservice-file-upload
  http:
    multipart:
      max-file-size: 2000Mb
      max-request-size: 2500Mb
eureka:
  client:
    service-url:
      defaultZone: http://user:123456@localhost:8070/eureka/
  instance:
    prefer-ip-address: true
management:
  security:
    enabled: false