spring:
  application:
    name: microservice-discovery-eureka-ha
---
spring:
  profiles: peer1
server:
  port: 8071
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://peer2:8072/eureka/
---
spring:
  profiles: peer2
server:
  port: 8072
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:8071/eureka/