server:
  port: 8040
spring:
  application:
    name: microservice-sidecar-node-service
eureka:
  client:
    service-url:
      defaultZone: http://user:123456@localhost:8070/eureka/
  instance:
    prefer-ip-address: true
sidecar:
  health-uri: http://localhost:8050/health.json
  port: 8050
  hostname: localhost
  ip-address: 192.168.118.1