
spring:
  application:
    name: microservice-hystrix-turbine
server:
  port: 8100
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:123456@localhost:8070/eureka
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    # 打印网络日志
    org.springframework.cloud.commons.util.InetUtils: TRACE
turbine:
  app-config: microservice-consumer-movie-feign-hystrix-fallback,microservice-consumer-movie-hystrix-fallback-factory
  cluster-name-expression: "'default'"
security:
  basic:
    enabled: false
