spring:
  application:
    name: microservice-discovery-eureka-authenticating
  profiles:
    active: localhost
security:
  basic:
    enabled: true
  user:
    name: user
    password: 123456

# 双节点Eureka Server 服务，相互注册，实现高可用
---
spring:
  profiles: peer1
server:
  port: 8071
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://peer2:8072/eureka/
---
spring:
  profiles: peer2
server:
  port: 8072
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:8071/eureka/
---
# 单节点
spring:
  profiles: localhost
server:
  port: 8070
eureka:
  instance:
    hostname: discovery
  client:
  #service-url:设置与Eureka Server 交互的网址，查询服务和注册服务都需要依赖这个地址，默认http://localhost:port/eureka；多个地址用','隔开*/
    service-url:
      defaultZone: http://discovery:8070/eureka/
    #register-with-eureka:表示是否将自己注册到Eureka Server,默认为true，这里是单节点设置为false
    register-with-eureka: false
    #fetch-registry:表示是否从Eureka Server 获取注册信息，默认为true，由于当前应用是单点的Eureka Server，不需要同步其他的Eureka Server 节点的数据，故设置为false
    fetch-registry: false

  #禁用自我保护模式
  server:
#    enable-self-preservation: false
    # 清理服务器
    eviction-interval-timer-in-ms: 5000
